
# list of utf-character that need to be deleted (such as interpuctuation)
characters_to_clean = ['\uf1f8', '\uf1ea', '\uf1f0', '\uf160', '\uf1f5', '\uf1e2', '\uf1e1']

# Define list of utf-character indicating abbreviated words (as dictionary for better readability)
special_characters_dictionary = {'-ur':'\uf1c2',
                                '-us':'\u1DD2',
                                '-bus':'\uf1ac',
                                '-rum':'\ua75D',
                                'b with stroke':'\u0180',
                                'd with stroke':'\u0111',
                                'h with stroke':'\u0127',
                                'K with stroke':'\uA740',
                                'k with stroke':'\uA741',
                                'l with stroke':'\uA749',
                                'Pre':'P\u0304',
                                'pre':'p\u0304',
                                'Per':'\uA750',
                                'per':'\uA751',
                                'Pro':'\uA752',
                                'pro':'\uA753',
                                'Nasalstoke':'\u0304',
                                'Abbreviationstroke':'\u0305',
                                'q with stroke':'\uA757',
                                'q with slipknot':'\uA759',
                                'Q mit Strich':'\uA756',
                                'Q mit Schlaufe':'\uA758',
                                '-a superscript':'\u1DD3',
                                '-i superscript':'\u0365',
                                '-o superscript':'\u0366',
                                '-u superscript':'\u0367'}

# Set rules for manual expansion
rules_for_expansion =  {'om̅': 'omn',
                        '\uf1c2': 'ur',
                        'P\u0304': 'Prae',
                        'p\u0304': 'prae',
                        '\uA750': 'Per',
                        '\uA751': 'per',
                        '\uA752': 'Pro',
                        '\uA753': 'pro',
                        '\u0304': 'm',
                        '\ua75D': 'rum',
                        'q\uf1ac': 'que',
                        'Q\u0366': 'Quo',
                        'q\u0366': 'quo',
                        'q\u1dd3': 'qua',
                        'Q\u1dd3': 'Qua',
                        'q\u0365': 'qui',
                        'p\u0365': 'pri',
                        'Q\u0365': 'Qui',
                        'b\uf1ac': 'bus',
                        '\u1DD2': 'us',
                        'c\u0305': 'con',
                        'C\u0305': 'Con',
                        'm\u0305': 'men',
                        't̅': 'ter',
                        'r̅': 'runt'}

characters_to_normalise = [['ę', 'ae'], ['vs', 'us'], ['bvs', 'bus'], ['vm', 'um'], ['Vt', 'Ut'], ['vt', 'ut'], ['mvr', 'mur'], ['tvr', 'tur'], [' uel', ' vel']]

verb_endings_to_normalise = [
                            ['auimus', 'avimus'],
                            ['auistis', 'avistis'],
                            ['auerunt', 'averunt'],
                            ['aueramus', 'averamus'],
                            ['aueratis', 'averatis'],
                            ['auerant', 'averant'],
                            ['auerimus', 'averimus'],
                            ['aueritis', 'averitis'],
                            ['auerint', 'averint'],
                            ['auissemus', 'avissemus'],
                            ['auissetis', 'avissetis'],
                            ['auissent', 'avissent'],
                            ['auisses', 'avisses'],
                            ['auissem', 'avissem'],
                            ['auisset', 'avisset'],
                            ['auit', 'avit'],
                            ['aueram', 'averam'],
                            ['aueras', 'averas'],
                            ['auerat', 'averat'],
                            ['auero', 'avero'],
                            ['aueris', 'averis'],
                            ['auerit', 'averit'],
                            ['auisti', 'avisti'],
                            ['auerim', 'averim'],
                            ['aui', 'avi'],
                            ['iuimus', 'ivimus'],
                            ['iuistis', 'ivistis'],
                            ['iuerunt', 'iverunt'],
                            ['iueramus', 'iveramus'],
                            ['iueratis', 'iveratis'],
                            ['iuerant', 'iverant'],
                            ['iuerimus', 'iverimus'],
                            ['iueritis', 'iveritis'],
                            ['iuerint', 'iverint'],
                            ['iuissemus', 'ivissemus'],
                            ['iuissetis', 'ivissetis'],
                            ['iuissent', 'ivissent'],
                            ['iuisses', 'ivisses'],
                            ['iuissem', 'ivissem'],
                            ['iuisset', 'ivisset'],
                            ['iuit', 'ivit'],
                            ['iueram', 'iveram'],
                            ['iueras', 'iveras'],
                            ['iuerat', 'iverat'],
                            ['iuero', 'ivero'],
                            ['iueris', 'iveris'],
                            ['iuerit', 'iverit'],
                            ['iuisti', 'ivisti'],
                            ['iuerim', 'iverim'],
                            ['iui', 'ivi'],
                            ['euimus', 'evimus'],
                            ['euistis', 'evistis'],
                            ['euerunt', 'everunt'],
                            ['eueramus', 'everamus'],
                            ['eueratis', 'everatis'],
                            ['euerant', 'everant'],
                            ['euerimus', 'everimus'],
                            ['eueritis', 'everitis'],
                            ['euerint', 'everint'],
                            ['euissemus', 'evissemus'],
                            ['euissetis', 'evissetis'],
                            ['euissent', 'evissent'],
                            ['euisses', 'evisses'],
                            ['euissem', 'evissem'],
                            ['euisset', 'evisset'],
                            ['euit', 'evit'],
                            ['eueram', 'everam'],
                            ['eueras', 'everas'],
                            ['euerat', 'everat'],
                            ['euero', 'evero'],
                            ['eueris', 'everis'],
                            ['euerit', 'everit'],
                            ['euisti', 'evisti'],
                            ['euerim', 'everim'],
                            ['eui', 'evi'],
                            ['tverunt', 'tuerunt']]






